### ISSUE TITLE
Cosmetic changes

### ISSUE THREAD

**Issue by key2market** [key2market/dataviz#16]
I would like to request a few cosmetic changes.
- Remove the edit connection button. Instead, editing the connection popup should be brought up by clicking the connection itself. Alternatively we can add the gear button right after the connection name.
- When clicking the button to edit the connection, the popup should show the Select Table or Custom SQL, depends on whether it is SQL or Table connection
- On the Select Table popup that shows the list of tables, there should be an Edit Connection so user can go back and adjust the the connection string if the user changed his mind about which server to connect to.
- Dimension and Metrics should be without border. It is great to have the gray background effect when cursor is above the field or when it is being dragged. But in the rested state, lets align them left and remove the border as per example in Dimensions in the attached image.
- Make the Left Side column a bit narrower and extend the chart area.
- Restore and Save buttons should be moved to the top and look sort of like a menu, rather than buttons without any borders etc. On click they Restore Chart should show a list of saved charts if available and No Charts Saved if empty. On click Save Chart should prompts for a chart name with "Please give this chart a name"

![example](https://cloud.githubusercontent.com/assets/16460237/12178428/b12558c2-b571-11e5-9c8d-1ac8a97da22e.jpg)

**Comment by prahladyeri** [comment]
Fixed. Feel free to test and reopen.

**Comment by key2market** [comment]
Hi Prahlad,
These changes are still not reflected. Can you pleae go through them one more time to ensure they are properly implemented.

**Comment by prahladyeri** [comment]
Have you tried the latest release version:

https://github.com/key2market/dataviz/archive/v1.2.zip

**Comment by prahladyeri** [comment]
Closing as found fixed in master branch. Feel free to reopen.

**Comment by key2market** [comment]
Dimension and Metrics should be left aligned

**Comment by prahladyeri** [comment]
As I said in a skype comment, there is still some ambiguity regarding this issue. In the above comment, you have mentioned that both "Dimension and Metrics should be left aligned". Whereas in the screen-shot you've pasted, the dimension is on the left, whereas metrics is on the right. Common sense says I should follow the screenshot, so that's what I'm doing now and fixing this. Please let me know if its otherwise and I'll revert back.
